apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: pacman
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: pacman
    app.kubernetes.io/part-of: mongo-pacman
  name: pacman
  namespace: user1-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: pacman
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: pacman
    spec:
      containers:
      - env:
        - name: MONGO_SERVICE_HOST
        image: quay.io/jduimovich0/pacman-frontend@sha256:c5aa31ddf701bce4af306b21bd2fba72d0093f021bf441379ebd9aac5125d09d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
